Added condition to Delivery insertion
YousefGamal220/Dentista pull request #16
Opened 2020-12-24 23:38 UTC by We2Am-BaSsem

I forgot to add the condition that the manager should be of type "Delivery" and manage the same area to get his id for the delivery insertion :D

2020-12-25 14:38 UTC, ahmedihabb2 approved these changes
-The main function inside store2 should be removed

2020-12-25 14:46 UTC, ahmedihabb2 requested changes
-The main function inside siqn2up should be removed

2020-12-26 14:05 UTC, YousefGamal220 approved these changes

2020-12-26 14:05 UTC, YousefGamal220 approved these changes

2020-12-26 14:06 UTC, YousefGamal220 approved these changes

2020-12-26 14:22 UTC, ahmedihabb2 approved these changes

2020-12-26 14:26 UTC, ahmedihabb2 approved these changes

2020-12-26 14:26 UTC, merged